[[LZO]]
arch = "x86_64"
git-tree-sha1 = "695d760d1e73424c8285c79dfa843d979bedcd3c"
libc = "glibc"
os = "linux"

    [[LZO.download]]
    sha256 = "051f1e2bdf58a68923dc00dfbc234cdff6d316fd4d2ef2f41d2dd7389165b8b0"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.x86_64-linux-gnu.tar.gz"
[[LZO]]
arch = "x86_64"
git-tree-sha1 = "ff1116a1fa25f7c3792705ec089666814353bd6b"
os = "macos"

    [[LZO.download]]
    sha256 = "456646ae7d9757d7d6a5464da661c9a408eba04a2deec004e06d76168940498d"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.x86_64-apple-darwin14.tar.gz"
[[LZO]]
arch = "i686"
git-tree-sha1 = "773936519f43d516af0c7c67bf578553fa35b5b8"
os = "windows"

    [[LZO.download]]
    sha256 = "a2a9733122da8120d9998e0054ec917d843664a7bf61bcea81cb06c1ea49dd1b"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.i686-w64-mingw32.tar.gz"
[[LZO]]
arch = "aarch64"
git-tree-sha1 = "72d0bd36ab5a1a226c80f1fb275209579a3b0771"
libc = "glibc"
os = "linux"

    [[LZO.download]]
    sha256 = "e52fa677da7ff05b34b9ece0687b115c14abe1c62c6c91d52fc44b8b62472efc"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.aarch64-linux-gnu.tar.gz"
[[LZO]]
arch = "i686"
git-tree-sha1 = "61f7588dc05cc6bddee83f24d7080beecc185b31"
libc = "musl"
os = "linux"

    [[LZO.download]]
    sha256 = "1af1f199194aba2adb83e7803e7109fee0d5ee0c624efa196835adf056d65909"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.i686-linux-musl.tar.gz"
[[LZO]]
arch = "x86_64"
git-tree-sha1 = "0586c16d0f3a53e926368f9a970f63c83549850e"
os = "windows"

    [[LZO.download]]
    sha256 = "fbe885b9cc97520878a0d5f89d0627247f93e77173e90792408b0f699428cc1f"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.x86_64-w64-mingw32.tar.gz"
[[LZO]]
arch = "powerpc64le"
git-tree-sha1 = "d7cb60fa84b8847dbad51845a3032e8f3bef88ba"
libc = "glibc"
os = "linux"

    [[LZO.download]]
    sha256 = "e10799a78fda02b6242aebec185ddfff2d346411eb19d13b8237a565e589bc6a"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.powerpc64le-linux-gnu.tar.gz"
[[LZO]]
arch = "x86_64"
git-tree-sha1 = "da9543077e282f80e151145c0ce73abee5898379"
os = "freebsd"

    [[LZO.download]]
    sha256 = "3c3c10321263962799c3b9b77a89f57df07fbaf6ca3e1eb7e9a867a90c252cb1"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LZO]]
arch = "armv7l"
git-tree-sha1 = "2b7f9ce78f630469ea17331b88d88884b65fb9bb"
libc = "musl"
os = "linux"

    [[LZO.download]]
    sha256 = "d2dfc002d422ff5609db189fd70ca3f324e93f3a315d1e59540471e454280980"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.arm-linux-musleabihf.tar.gz"
[[LZO]]
arch = "aarch64"
git-tree-sha1 = "f7aabc627a43a6b3541203f8837a1885ccb62f1a"
libc = "musl"
os = "linux"

    [[LZO.download]]
    sha256 = "3914e96ddd370014ebd45b8a2dcfdd4f58e36f16c5e329f9cb78e32cd5e4b162"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.aarch64-linux-musl.tar.gz"
[[LZO]]
arch = "i686"
git-tree-sha1 = "3ecfdb83204acc87be7921d389b57ac482910f11"
libc = "glibc"
os = "linux"

    [[LZO.download]]
    sha256 = "68b8e3985c9b3a679aa94f845ca59cb344c24f62cc72a983ad9d94893ab238db"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.i686-linux-gnu.tar.gz"
[[LZO]]
arch = "x86_64"
git-tree-sha1 = "481ecb1a2720b85bb62509a26ed69cf4f8ae618f"
libc = "musl"
os = "linux"

    [[LZO.download]]
    sha256 = "e5681aab8c4fe7cc948c47dbe8052aa72c71912538af4c8b7a9c7da8b9e7c7f6"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.x86_64-linux-musl.tar.gz"
[[LZO]]
arch = "armv7l"
git-tree-sha1 = "20b4e1cdb5d4d156a707ccfc5f8a180c3702ff4b"
libc = "glibc"
os = "linux"

    [[LZO.download]]
    sha256 = "cabafde36a75013a290795a044c464d52a75af8d2e7a65f403311b0c51a48caf"
    url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.0+0/LZO.v2.10.0.arm-linux-gnueabihf.tar.gz"
